use std::fs;
use std::path::Path;

fn main() {
    let plugins_dir = "src/plugins";
    let dest_path = Path::new("src/plugins/generated.rs");

    let mut plugin_mods = String::new();
    let mut plugin_creations = String::new();

    if let Ok(entries) = fs::read_dir(plugins_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                let name = path.file_name().unwrap().to_str().unwrap();
                if name != "core" && name != "generated" {
                    // 生成条件编译标签，格式为 plugin_插件文件夹名
                    let feature_gate = format!("#[cfg(feature = \"plugin_{}\")]", name);
                    
                    plugin_mods.push_str(&format!("{}\npub mod {};\n", feature_gate, name));

                    plugin_creations.push_str(&format!("        {}\n", feature_gate));
                    plugin_creations.push_str(&format!("        Box::new({}::create()),\n", name));
                }
            }
        }
    }

    let mut content = String::new();
    content.push_str("// Generated by build.rs. DO NOT EDIT.\n\n");
    content.push_str(&plugin_mods);
    content.push_str("\npub fn get_extra_plugins() -> Vec<Box<dyn crate::Plugin>> {\n");
    content.push_str("    vec![\n");
    content.push_str(&plugin_creations);
    content.push_str("    ]\n");
    content.push_str("}
");

    fs::write(dest_path, content).unwrap();
    println!("cargo:rerun-if-changed={}", plugins_dir);
}