use std::fs;
use std::path::Path;

fn main() {
    let plugins_dir = "src/plugins";
    let dest_path = Path::new("src/plugins/generated.rs");

    let mut plugin_mods = String::new();
    let mut plugin_creations = String::new();

    if let Ok(entries) = fs::read_dir(plugins_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                let name = path.file_name().unwrap().to_str().unwrap();
                if name != "core" && name != "generated" {
                    plugin_mods.push_str("pub mod ");
                    plugin_mods.push_str(name);
                    plugin_mods.push_str(";\n");

                    plugin_creations.push_str("        Box::new(");
                    plugin_creations.push_str(name);
                    plugin_creations.push_str("::create()),\n");
                }
            }
        }
    }

    let mut content = String::new();
    content.push_str("// Generated by build.rs. DO NOT EDIT.\n\n");
    content.push_str(&plugin_mods);
    content.push_str("\npub fn get_extra_plugins() -> Vec<Box<dyn crate::Plugin>> {\n");
    content.push_str("    vec![\n");
    content.push_str(&plugin_creations);
    content.push_str("    ]\n");
    content.push_str("}\n");

    fs::write(dest_path, content).unwrap();
    println!("cargo:rerun-if-changed={}", plugins_dir);
}
