// Generated by build.rs. DO NOT EDIT.

#[cfg(feature = "plugin_code_editor")]
pub mod code_editor;
#[cfg(feature = "plugin_test_plugin")]
pub mod test_plugin;

pub fn get_extra_plugins() -> Vec<Box<dyn crate::Plugin>> {
    vec![
        #[cfg(feature = "plugin_code_editor")]
        Box::new(code_editor::create()),
        #[cfg(feature = "plugin_test_plugin")]
        Box::new(test_plugin::create()),
    ]
}
